# Imagen base con Java 21
FROM eclipse-temurin:21-jdk-alpine

# Carpeta de trabajo
WORKDIR /app

# Copiar archivos del proyecto
COPY pom.xml .
COPY src ./src

# Descargar dependencias y compilar
RUN apk add --no-cache maven
RUN mvn clean package -DskipTests

# Exponer el puerto
EXPOSE 8080

# Comando para ejecutar la app
CMD ["java", "-jar", "target/app.jar"]